source "https://rubygems.org"

gem "lita"
gem "lita-directions"
gem "lita-google-images"
gem "lita-answers"
gem "lita-forecast"
gem "lita-google"
gem "lita-memegen"
gem "lita-pivotal-tracker"
gem "lita-quote"
gem "lita-stocks"
gem "lita-urban-dictionary"
gem "lita-wikipedia"
gem "lita-yo"
gem "lita-youtube"
gem "lita-clever"
gem "lita-slack"